import { gmGetValue } from "./lib/gm.ts";
export const CONFIG_KEYS = [
  "ACTIVE_SCRIPTS",
  "BETTER_INTRA_THEME",
  "LOGTIME_GOAL_HOURS",
  "LOGTIME_SHOW_AVERAGE",
  "LOGTIME_SHOW_GOAL",
  "DISABLE_ANIMATIONS",
  "LOGTIME_SHOW_TACOS",
  "LOGTIME_EMOJI",
  "LOGTIME_EMOJI_DIVISOR",
  "LOGTIME_EMOJI_RATE",
  "LOGTIME_SHOW_DAYS_MODE",
  "LOGTIME_CALENDAR_COLOR",
  "LOGTIME_LABELS_COLOR",
  "CLUSTERS_SHOW_MARKERS",
  "CLUSTERS_DEFAULT_ID",
  "PROFILE_CAMPUS_FILTER",
  "PROFILE_EVENT_TYPE_FILTER",
  "PROFILE_IMAGE_URL",
  "PROFILE_BANNER_URL",
  "PROFILE_BACKGROUND_URL",
  "PROFILE_SLOTS_REDIRECTION",
  "SHORTCUTS_LINKS",
  "ACCOUNT",
  "CLOUD_SYNC_ENABLED",
  "CLOUD_PASSWORD",
  "LAST_CLOUD_SYNC",
] as const;

export type ConfigKey = (typeof CONFIG_KEYS)[number];

export const CONFIG_DEFAULT: Record<ConfigKey, any> = {
  ACTIVE_SCRIPTS: '["logtime", "clusters", "profile", "shortcuts", "account"]',
  CLOUD_SYNC_ENABLED: false,
  CLOUD_PASSWORD: "",
  LAST_CLOUD_SYNC: null,
  ACCOUNT: null,

  LOGTIME_GOAL_HOURS: 140,
  LOGTIME_SHOW_AVERAGE: true,
  LOGTIME_SHOW_GOAL: true,
  DISABLE_ANIMATIONS: false,
  LOGTIME_SHOW_TACOS: false,
  LOGTIME_EMOJI: "🌮",
  LOGTIME_EMOJI_DIVISOR: 8.7,
  LOGTIME_EMOJI_RATE: 2,
  LOGTIME_SHOW_DAYS_MODE: "date",
  LOGTIME_CALENDAR_COLOR: "#00BCBA",
  LOGTIME_LABELS_COLOR: "#26a641",

  CLUSTERS_SHOW_MARKERS: true,
  CLUSTERS_DEFAULT_ID: "",

  PROFILE_CAMPUS_FILTER: "all",
  PROFILE_EVENT_TYPE_FILTER: "all",
  PROFILE_IMAGE_URL: "",
  PROFILE_BANNER_URL: "",
  PROFILE_BACKGROUND_URL: "",
  PROFILE_SLOTS_REDIRECTION: true,

  BETTER_INTRA_THEME: "dark",
  SHORTCUTS_LINKS: "[]",
};

export const getConfig = async <T extends ConfigKey>(key: T): Promise<typeof CONFIG_DEFAULT[T]> => {
  return await gmGetValue(key, CONFIG_DEFAULT[key]);
};