name: Build
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Userscript
        run: npm run build 

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: dist/*.user.js

      - name: Upload to Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v3
        with:
          files: dist/*.user.js